# services:
  - type: web
    name: django-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: bash -c "python manage.py migrate && gunicorn backend.wsgi:application"

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        value: your-django-secret-key
      - key: ALLOWED_HOSTS
        value: skillup-website.onrender.com
      - key: DEBUG
        value: "False"

  - type: web
    name: react-frontend
    env: static
    buildCommand: cd skilup-frontend && npm install && npm run build
    staticPublishPath: skilup-frontend/dist
